### ISSUE TITLE
Bold font offset in Gboard

### ISSUE THREAD

**Issue by kleest** [Magisk-Modules-Repo/SanFrancisco_Fonts#8]
First of all, thank you for this module!

I noticed a small issue when using Gboard with this module: The bold word suggestion in Gboard is a few pixels off on my device. I haven't experienced this issue at other places, yet.

Device: OnePlus 6
ROM: OxygenOS 9.0.9
Android: 9
Font scale: 1.0
PPI: 420

Do you need additional information?

![fontbold_offset](https://user-images.githubusercontent.com/6516878/67608108-241c7080-f787-11e9-910e-ba0bcc38573c.png)

**Comment by cptmacp** [comment]
@kleest 
I have address these issue s, please try the latest SF and let me know 

Holding the issue ATM

**Comment by kleest** [comment]
It's way better. However, there is still a little offset.

from left to right: normal font, bold font (old version), bold font (newest version, ca94454477334bbdf41d7e6afaf5e32a3118ea78).
![fontbold_offset2](https://user-images.githubusercontent.com/6516878/68401914-d2a6b500-017a-11ea-8115-a438c3ad6eb1.png)

**Comment by cptmacp** [comment]
that itself cant be touched , because apple uses very different way of using font view 
its noway near android.view which are used in android system and its parts 

little bit change in metrices cause a lot of issue with glyph 

and not to mention how much reworked they are now as comparted to last 2 years SF

let me know if have any other querry
